apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}-headless
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongo
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name }}